services:
  - type: web
    name: merchant-erp-backend
    env: node
    region: oregon
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        value: mongodb+srv://asadalirustam9_db_user:asadali456@cluster0.7ktiiem.mongodb.net/Shop?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        value: merchant_secret_access_key_9988776655
      - key: JWT_REFRESH_SECRET
        value: merchant_secret_refresh_key_5544332211
